### ISSUE TITLE
Error: Manual TreeTagger configuration: "en" is not a valid preset!

### ISSUE THREAD

**Issue by JasonScottSchneider** [unDocUMeantIt/koRpus#17]
For some reason, it says that "en" is not a valid preset for a manual treetagger configuration. The same problem was reported for issue #15. I tried loading the library(koRpus.lang.en), but this didn't help me. Furthermore, I made sure to set the path to where I have the folder for TreeTagger in the batches and environmental variables. (Windows 7 and R 3.4.4)
![korpus](https://user-images.githubusercontent.com/43894195/52159477-b2d1e600-266a-11e9-8a41-a82e1c499b37.jpg)

_Originally posted by @JasonScottSchneider in https://github.com/unDocUMeantIt/koRpus/issues/15#issuecomment-459932112_

**Comment by JasonScottSchneider** [comment]
I had originally placed the folder TreeTagger in Program Files, but I moved it to root C:\TreeTagger to trouble shoot whether this could have any effects, which it didn't help either. I had remembered to set the path for environmental variables and the batches after moving the folder, too.
![korpus2](https://user-images.githubusercontent.com/43894195/52159908-6f7a7600-2670-11e9-8289-c0b9a2965970.jpg)

**Comment by JasonScottSchneider** [comment]
I am not sure what I was doing wrong, but, after running this (see below), the error no longer appears.

# install the language support package
install.koRpus.lang("en")
# load the package
library(koRpus.lang.en)

          from https://cran.r-project.org/web/packages/koRpus/vignettes/koRpus_vignette.html

I might have typed something incorrectly before. I wonder whether having both libraries koRpus and koRpus.lang.en active might have been the issue. However, I have it working now.
![korpus3](https://user-images.githubusercontent.com/43894195/52160009-64c0e080-2672-11e9-9d37-80d494d299e2.jpg)

**Comment by unDocUMeantIt** [comment]
glad you figured it out. looking at your first two screenshots, i actually don't see you calling `library(koRpus.lang.en)` anywhere. it looks more like you were only installing the package, but not loading it, hence the error message.

there is no harm in loading both koRpus and any of the language packages at once (load as many as you like). in fact, you don't need to load koRpus separately, because it will be loaded automatically as a dependency when you load any koRpus.lang.* package. i.e., it's impossible to use those without koRpus being loaded.
