### ISSUE TITLE
Incorrect calculation of MTLD?

### ISSUE THREAD

**Issue by mrkm-a** [unDocUMeantIt/koRpus#30]
Thank you for a useful package. 

I noticed a discrepancy in the calculation of MTLD between the algorithm explained in [McCarthy and Jarvis's (2010) paper](https://link.springer.com/article/10.3758/BRM.42.2.381) and the way `koRpus::MTLD.calc()` calculates it.

On McCarthy and Jarvis (2010, p.385):

> The total number of words in the text is divided by the total factor count. For example, if the text = 340 words and the factor count = 4.404, then the MTLD value is 77.203. Two such MTLD values are calculated, one for forward processing and one for reverse processing. The mean of the two values is the final MTLD value.

So it is the two MTLD values (i.e., forward and reverse) whose mean should be calculated. 

On the other hand, the relevant part in `koRpus::MTLD.calc()` calculates the mean of two factors (i.e., denominators), and the number of tokens is divided by the mean factor:

`mtld.res.mean <- mean(c(mtld.res.forw[["factors"]], mtld.res.back[["factors"]]))`
`mtld.res.value <- num.tokens/mtld.res.mean`

The two methods yield different results as `mean(c(N/f1, N/f2))` and `N/mean(c(f1, f2))` are different. 

If this is not by design, would you mind fixing the issue when you can?

**Comment by unDocUMeantIt** [comment]
from just reading it this sound like a good point. yet it would surprise me a bit, because mccarthy and jarvis kindly helped me validate my implementation by comparing results with their original implementation, for both MTLD and MTLD-MA. since there's unit tests in the package, i'd assume there have not been undetected changes in the implementation since.

i'll have to dig deeper into my mail archive and examine the actual calcualtions in more detail. stay tuned ;)

**Comment by unDocUMeantIt** [comment]
i stand surprised. going back through the mails we exchanged back then, we actually wondered about that *slight* mismatch of results (about 0.1-0.5%) we all assumed were due to different methods of tokenizing (e.g., it's roughly the effective difference between counting +/- 1 token of a 500 token text) or cumulated rounding differences, but nothing systematic. i re-ran the tests from then and this actually solves the miracle.

thank you very much for reporting this! and btw, this was an excellent bug report, i knew exactly where to look and why, this made it very easy for me to track down the issue and fix it. i'm glad you were able to read my code. please let me know if you find more bugs :)

**Comment by mrkm-a** [comment]
I'm glad my report helped. Thank you for looking into the issue so promptly and also for developing and maintaining this excellent package.
